apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway1
  template:
    metadata:
      labels:
        app: gateway1
    spec:
      containers:
      - name: gateway1
        image: gcr.io/oceanic-craft-302516/gateway1:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always